# Site settings
title: HantaoSun's Blog
email: jhkghmn@gmail.com
description: Loading Life
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: sunhantao
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/sunhantao/sunhantao.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/sunhantao/sunhantao.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com.
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: Loading
disqus_url: "http://sunhantao.github.io"
#########################################

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "fenced_code_blocks"]
# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
